# Generated by Django 4.2.4 on 2023-08-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctioncategory_auctionlisting_comment_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='auctions.auctionlisting'),
        ),
    ]
