# Generated by Django 4.2.4 on 2023-08-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlisting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='photo',
            field=models.URLField(default='', max_length=256),
        ),
    ]
