# Generated by Django 4.2.4 on 2023-08-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlisting_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='photo',
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
