# Generated by Django 4.2.4 on 2023-08-24 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlisting_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 24, 2, 43, 1, 380651, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
